// Code generated by "enumer -type=LandType"; DO NOT EDIT.

package land_type

import (
	"fmt"
	"strings"
)

const _LandTypeName = "JungleWetlandsDesertMountainOcean"

var _LandTypeIndex = [...]uint8{0, 6, 14, 20, 28, 33}

const _LandTypeLowerName = "junglewetlandsdesertmountainocean"

func (i LandType) String() string {
	if i < 0 || i >= LandType(len(_LandTypeIndex)-1) {
		return fmt.Sprintf("LandType(%d)", i)
	}
	return _LandTypeName[_LandTypeIndex[i]:_LandTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LandTypeNoOp() {
	var x [1]struct{}
	_ = x[Jungle-(0)]
	_ = x[Wetlands-(1)]
	_ = x[Desert-(2)]
	_ = x[Mountain-(3)]
	_ = x[Ocean-(4)]
}

var _LandTypeValues = []LandType{Jungle, Wetlands, Desert, Mountain, Ocean}

var _LandTypeNameToValueMap = map[string]LandType{
	_LandTypeName[0:6]:        Jungle,
	_LandTypeLowerName[0:6]:   Jungle,
	_LandTypeName[6:14]:       Wetlands,
	_LandTypeLowerName[6:14]:  Wetlands,
	_LandTypeName[14:20]:      Desert,
	_LandTypeLowerName[14:20]: Desert,
	_LandTypeName[20:28]:      Mountain,
	_LandTypeLowerName[20:28]: Mountain,
	_LandTypeName[28:33]:      Ocean,
	_LandTypeLowerName[28:33]: Ocean,
}

var _LandTypeNames = []string{
	_LandTypeName[0:6],
	_LandTypeName[6:14],
	_LandTypeName[14:20],
	_LandTypeName[20:28],
	_LandTypeName[28:33],
}

// LandTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LandTypeString(s string) (LandType, error) {
	if val, ok := _LandTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LandTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LandType values", s)
}

// LandTypeValues returns all values of the enum
func LandTypeValues() []LandType {
	return _LandTypeValues
}

// LandTypeStrings returns a slice of all String values of the enum
func LandTypeStrings() []string {
	strs := make([]string, len(_LandTypeNames))
	copy(strs, _LandTypeNames)
	return strs
}

// IsALandType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LandType) IsALandType() bool {
	for _, v := range _LandTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
